<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **1ste Portofolio opdracht**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## **Teamnaam: The GOAT**

### **Auteurs**

- Robin Djerahian (25045490)
- Aimée Pauly (25086103)
- Jinke Westendorp (23148063)

### **Kaggle Gebruikersnamen**

- Robin Djerahian
- plplplp78y87
- Jinke Westendorp

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **1. Inleiding**

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

MedPredict is een medisch technologiebedrijf dat ziekenhuizen en zorginstellingen ondersteunt bij het vroegtijdig herkennen van gezondheidsrisico’s. Het bedrijf werkt met geanonimiseerde patiëntgegevens. Deze gegevens bevatten onder andere demografische kenmerken, leefstijlfactoren en medische informatie.

MedPredict wil onderzoeken of deze gegevens kunnen worden gebruikt om patiënten met een verhoogd risico op een herseninfarct (stroke) vroegtijdig te herkennen.

Tot nu toe wordt het risico op een herseninfarct beoordeeld door zorgprofessionals op basis van medische informatie en hun eigen kennis. Dit proces kan veel tijd kosten, vooral wanneer grote aantallen patiëntgegevens moeten worden bekeken.

MedPredict heeft de opdracht gegeven om een machine-learningmodel te ontwikkelen dat voorspelt of een patiënt een verhoogd risico op een herseninfarct heeft. Het model gebruikt hiervoor de beschikbare persoonsgegevens uit de dataset.

Ons team werkt als junior data scientists aan deze opdracht. We analyseren de data, vergelijken verschillende machine-learningmodellen en beoordelen welke aanpak het beste werkt.

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **2. Probleemstelling**

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

MedPredict heeft behoefte aan een betrouwbaar machine-learningmodel dat:

- patiënten met een verhoogd risico op een herseninfarct zo nauwkeurig mogelijk voorspelt;
- foutieve voorspellingen zoveel mogelijk beperkt;
- zorgprofessionals ondersteunt bij het vroegtijdig herkennen en opvolgen van risicopatiënten.

Onze taak is om een machine-learningmodel te bouwen en te evalueren dat voorspelt of een patiënt een herseninfarct heeft gehad of een verhoogd risico daarop heeft.

Het model gebruikt hiervoor de beschikbare geanonimiseerde patiëntgegevens. Deze gegevens bevatten onder andere de volgende soorten kenmerken:

- demografische gegevens, zoals leeftijd en geslacht;
- leefstijlfactoren, zoals rookgedrag;
- medische informatie, zoals hoge bloeddruk, hartaandoeningen en gemiddelde glucosespiegel.

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **3. De Datasets**

In [2]:
# Packages importeren 
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

# Datasets importeren
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
submission_df = pd.read_csv("sample_submission.csv")

## Train_df

Deze dataset bestaat uit:
- 33550 observaties van patiënten in train.csv
- 1 doelvariabele: **stroke**
    - 0 betekent dat de patiënt geen herseninfarct heeft gehad
    - 1 betkent dat de patiënt wel een herseninfarct heeft gehad
- 21 kenmerken die worden gebruikt om een voorspelling te maken
- Zowel numerieke als binaire kenmerken (True of False)

In [6]:
display(train_df.head())
print(train_df.shape)

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,52709,30.0,0,0,63.60,33.3,False,True,False,True,False,False,False,True,False,False,True,False,False,False,True,0
1,72295,75.0,1,0,215.17,48.0,True,False,False,False,True,False,False,False,True,False,True,False,False,True,False,0
2,26451,15.0,0,0,135.22,19.0,False,True,False,True,False,False,False,True,False,False,True,False,False,True,False,0
3,65210,47.0,0,0,64.89,28.2,False,True,False,False,True,False,False,False,True,False,False,True,False,True,False,0
4,69299,49.0,0,0,222.34,28.8,False,True,False,False,True,False,False,False,True,False,True,False,True,False,False,0

(33550, 22)

## Test_df

De dataset test.csv bevat gegevens van patiënten waarvoor de kolom **stroke** ontbreekt. Deze dataset heeft dezelfde kenmerken als train.csv.

We gebruiken test.csv niet om het model te trainen. Nadat we het beste model hebben gekozen, gebruiken we deze dataset om per patiënt een voorspelling te maken. De voorspellingen zetten we vervolgens in een kaggle-submissionbestand

In [4]:
display(test_df.head())
print(test_df.shape)

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,32840,52.0,0,0,97.32,21.8,True,False,False,False,True,False,False,True,False,False,False,True,False,False,True
1,45158,30.0,0,0,227.99,47.7,True,False,False,False,True,False,False,True,False,False,False,True,False,False,True
2,56105,26.0,0,0,113.28,24.4,True,False,False,False,True,False,False,True,False,False,False,True,False,True,False
3,3112,24.0,0,0,79.15,21.0,True,False,False,False,True,False,False,True,False,False,False,True,True,False,False
4,35224,63.0,0,0,89.69,33.3,True,False,False,False,True,False,False,True,False,False,False,True,False,True,False

(8388, 21)

## Submission_df

De dataset **sample_submission.csv** laat zien hoe het bestand voor de Kaggle-inlevering eruit moet zien. Dit bestand bevat twee kolommen:
- **id**: Het unieke patiëntnummer uit test.csv
- **stroke**: De voorspelling van ons model

In [5]:
display(submission_df.head())
print(submission_df.shape)

      id  stroke
0  32840       1
1  45158       0
2  56105       1
3   3112       0
4  35224       1

(8388, 2)

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **4. Exploratieve data-analyse (EDA)**

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

In dit hoofdstuk onderzoeken we de dataset voordat we modellen gaan maken. Dit noemen we Exploratieve Data Analyse, oftewel EDA.

We bekijken onder andere de datatypes, missende waarden, dubbele rijen en basisstatistieken. Ook onderzoeken we hoe de verschillende kenmerken, zoals leeftijd, BMI, hoge bloeddruk en rookgedrag, samenhangen met de kolom **stroke**.

Met grafieken en tabellen krijgen we een beter beeld van de data. De belangrijkste bevindingen gebruiken we daarna bij het opschonen, voorbereiden en trainen van onze machine-learningmodellen.

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 4.1 Uitleg van de kolommen

Hierbij kijken wij alleen naar de dataframe **Train_df**

| Kolom | Betekenis | Meetniveau | Type |
|---|---|---|---|
| `id` | Uniek nummer van de patiënt. Deze kolom gebruik je niet als invoerkenmerk voor het model. | Nominaal | Integer |
| `age` | Leeftijd van de patiënt in jaren. | Ratio | Numeriek (float) |
| `hypertension` | Of de patiënt hoge bloeddruk heeft: `0` = nee, `1` = ja. | Nominaal | Binair (integer) |
| `heart_disease` | Of de patiënt een hartaandoening heeft: `0` = nee, `1` = ja. | Nominaal | Binair (integer) |
| `avg_glucose_level` | Gemiddelde bloedsuikerspiegel van de patiënt. | Ratio | Numeriek (float) |
| `bmi` | Body Mass Index van de patiënt. | Ratio | Numeriek (float) |
| `gender_Female` | Of de patiënt vrouw is: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `gender_Male` | Of de patiënt man is: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `gender_Other` | Of de patiënt een ander geslacht heeft: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `ever_married_No` | Of de patiënt nooit getrouwd is geweest: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `ever_married_Yes` | Of de patiënt ooit getrouwd is geweest: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `work_type_Govt_job` | Of de patiënt bij de overheid werkt: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `work_type_Never_worked` | Of de patiënt nooit heeft gewerkt: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `work_type_Private` | Of de patiënt in de private sector werkt: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `work_type_Self-employed` | Of de patiënt zelfstandig werkt: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `work_type_children` | Of de patiënt in de categorie kinderen valt: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `Residence_type_Rural` | Of de patiënt in een landelijk gebied woont: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `Residence_type_Urban` | Of de patiënt in een stedelijk gebied woont: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `smoking_status_formerly smoked` | Of de patiënt vroeger rookte: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `smoking_status_never smoked` | Of de patiënt nooit heeft gerookt: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `smoking_status_smokes` | Of de patiënt momenteel rookt: `False` = nee, `True` = ja. | Nominaal | Binair (boolean) |
| `stroke` | Doelvariabele: of de patiënt een herseninfarct heeft gehad: `0` = nee, `1` = ja. | Nominaal | Binair (integer) |

> De kolommen die beginnen met `gender_`, `ever_married_`, `work_type_`, `Residence_type_` en `smoking_status_` zijn dummyvariabelen. Zij zijn gemaakt door categorische gegevens om te zetten naar `True` en `False`-kolommen.

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 4.2 Controle van de data

In [7]:
# controle datatypes
train_df.dtypes

id                                  int64
age                               float64
hypertension                        int64
heart_disease                       int64
avg_glucose_level                 float64
bmi                               float64
gender_Female                        bool
gender_Male                          bool
gender_Other                         bool
ever_married_No                      bool
ever_married_Yes                     bool
work_type_Govt_job                   bool
work_type_Never_worked               bool
work_type_Private                    bool
work_type_Self-employed              bool
work_type_children                   bool
Residence_type_Rural                 bool
Residence_type_Urban                 bool
smoking_status_formerly smoked       bool
smoking_status_never smoked          bool
smoking_status_smokes                bool
stroke                              int64
dtype: object

In [11]:
# Missende waardes checken
train_df.isnull().sum()

id                                0
age                               0
hypertension                      0
heart_disease                     0
avg_glucose_level                 0
bmi                               0
gender_Female                     0
gender_Male                       0
gender_Other                      0
ever_married_No                   0
ever_married_Yes                  0
work_type_Govt_job                0
work_type_Never_worked            0
work_type_Private                 0
work_type_Self-employed           0
work_type_children                0
Residence_type_Rural              0
Residence_type_Urban              0
smoking_status_formerly smoked    0
smoking_status_never smoked       0
smoking_status_smokes             0
stroke                            0
dtype: int64

In [12]:
# Duplicaten checken
train_df.duplicated().sum()

np.int64(0)

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 4.3 Basisstatistieken

In [14]:
# Basisinformatie over alle kolommen
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33550 entries, 0 to 33549
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              33550 non-null  int64
 1   age                             33550 non-null  float64
 2   hypertension                    33550 non-null  int64
 3   heart_disease                   33550 non-null  int64
 4   avg_glucose_level               33550 non-null  float64
 5   bmi                             33550 non-null  float64
 6   gender_Female                   33550 non-null  bool
 7   gender_Male                     33550 non-null  bool
 8   gender_Other                    33550 non-null  bool
 9   ever_married_No                 33550 non-null  bool
 10  ever_married_Yes                33550 non-null  bool
 11  work_type_Govt_job              33550 non-null  bool
 12  work_type_Never_worked          33550 non-null  bool
 13  work_type_Private               33550 non-null  bool
 14  work_type_Self-employed         33550 non-null  bool
 15  work_type_children              33550 non-null  bool
 16  Residence_type_Rural            33550 non-null  bool
 17  Residence_type_Urban            33550 non-null  bool
 18  smoking_status_formerly smoked  33550 non-null  bool
 19  smoking_status_never smoked     33550 non-null  bool
 20  smoking_status_smokes           33550 non-null  bool
 21  stroke                          33550 non-null  int64
dtypes: bool(15), float64(3), int64(4)
memory usage: 2.3 MB

In [15]:
# Basisstatistieken van numerieke kolommen
display(train_df.describe())

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,33550.000000,33550.000000,33550.000000,33550.000000,33550.000000,33550.000000,33550.000000
mean,36746.393353,41.815312,0.088137,0.043040,103.587081,28.601216,0.015410
std,20906.519131,22.477423,0.283498,0.202951,42.127396,7.782248,0.123178
min,1.000000,0.080000,0.000000,0.000000,55.010000,10.100000,0.000000
25%,18763.250000,24.000000,0.000000,0.000000,77.460000,23.300000,0.000000
50%,36862.000000,43.000000,0.000000,0.000000,91.320000,27.700000,0.000000
75%,54757.500000,59.000000,0.000000,0.000000,111.437500,32.800000,0.000000
max,72943.000000,82.000000,1.000000,1.000000,281.590000,97.600000,1.000000

In [16]:
# Basisstatistieken inclusief booleaanse kolommen
display(train_df.describe(include="all"))

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
count,33550.000000,33550.000000,33550.000000,33550.000000,33550.000000,33550.000000,33550,33550,33550,33550,33550,33550,33550,33550,33550,33550,33550,33550,33550,33550,33550,33550.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,False,True,False,False,True,False,False,False,True,False,False,False,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,20032,20038,33544,21426,21426,29394,33409,19279,28424,28702,16776,16776,27889,20948,28583,NaN
mean,36746.393353,41.815312,0.088137,0.043040,103.587081,28.601216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.015410
std,20906.519131,22.477423,0.283498,0.202951,42.127396,7.782248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.123178
min,1.000000,0.080000,0.000000,0.000000,55.010000,10.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,18763.250000,24.000000,0.000000,0.000000,77.460000,23.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,36862.000000,43.000000,0.000000,0.000000,91.320000,27.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,54757.500000,59.000000,0.000000,0.000000,111.437500,32.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
max,72943.000000,82.000000,1.000000,1.000000,281.590000,97.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **5. Preprocessing & train-test split**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **6. Modelontwikkeling**

In dit hoofdstuk bouwen en vergelijken we verschillende machine-learningmodellen. Het doel van deze modellen is om te voorspellen of een patiënt een verhoogd risico heeft op een herseninfarct.

We gebruiken de opgeschoonde en voorbereide data uit het vorige hoofdstuk. Voor elk model trainen we het model met de trainset en bekijken we daarna hoe goed het model presteert op onze eigen testset.

We vergelijken onder andere k-Nearest Neighbors, Logistic Regression, Support Vector Machine, Decision Tree, Random Forest, Gradient Boosted Decision Trees en XGBoost. Ook maken we een eigen ensemble met meerdere modellen.

Omdat de dataset ongebalanceerd is, passen we bij elk model technieken toe om beter om te gaan met de kleinere groep patiënten met stroke = 1. Daarnaast gebruiken we cross-validation en hyperparameter tuning om de modellen te verbeteren.

Uiteindelijk vergelijken we de resultaten van alle modellen. Het beste model gebruiken we om voorspellingen te maken voor test.csv en in te leveren bij Kaggle.

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.1 K-Nearest Neighbors

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.2 Logistic Regression

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.3 Support Vector Machine (SVM)

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.4 Decision Tree

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.5 Random Forest

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.6 Gradient Boosted Decision Trees

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.7 XGBoost

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.8 Zelf samengestelde ensemble

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **7. Model Evaluatie**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **8. Modelinterpretatie**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **9. Conclusie & aanbeveling**