<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **1ste Portofolio opdracht**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **Auteurs**

- Robin Djerahian (25045490)
- Aimée Pauly (25086103)
- Jinke Westendorp (23148063)

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **1. Inleiding**

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

MedPredict is een medisch technologiebedrijf dat ziekenhuizen en zorginstellingen ondersteunt bij het vroegtijdig herkennen van gezondheidsrisico’s. Het bedrijf werkt met geanonimiseerde patiëntgegevens. Deze gegevens bevatten onder andere demografische kenmerken, leefstijlfactoren en medische informatie.

MedPredict wil onderzoeken of deze gegevens kunnen worden gebruikt om patiënten met een verhoogd risico op een herseninfarct (stroke) vroegtijdig te herkennen.

Tot nu toe wordt het risico op een herseninfarct beoordeeld door zorgprofessionals op basis van medische informatie en hun eigen kennis. Dit proces kan veel tijd kosten, vooral wanneer grote aantallen patiëntgegevens moeten worden bekeken.

MedPredict heeft de opdracht gegeven om een machine-learningmodel te ontwikkelen dat voorspelt of een patiënt een verhoogd risico op een herseninfarct heeft. Het model gebruikt hiervoor de beschikbare persoonsgegevens uit de dataset.

Ons team werkt als junior data scientists aan deze opdracht. We analyseren de data, vergelijken verschillende machine-learningmodellen en beoordelen welke aanpak het beste werkt.

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **2. Probleemstelling**

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

MedPredict heeft behoefte aan een betrouwbaar machine-learningmodel dat:

- patiënten met een verhoogd risico op een herseninfarct zo nauwkeurig mogelijk voorspelt;
- foutieve voorspellingen zoveel mogelijk beperkt;
- zorgprofessionals ondersteunt bij het vroegtijdig herkennen en opvolgen van risicopatiënten.

Onze taak is om een machine-learningmodel te bouwen en te evalueren dat voorspelt of een patiënt een herseninfarct heeft gehad of een verhoogd risico daarop heeft.

Het model gebruikt hiervoor de beschikbare geanonimiseerde patiëntgegevens. Deze gegevens bevatten onder andere de volgende soorten kenmerken:

- demografische gegevens, zoals leeftijd en geslacht;
- leefstijlfactoren, zoals rookgedrag;
- medische informatie, zoals hoge bloeddruk, hartaandoeningen en gemiddelde glucosespiegel.

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **3. De Datasets**

In [1]:
# Packages importeren 
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

# Datasets importeren
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
submission_df = pd.read_csv("sample_submission.csv")

## Train_df

Deze dataset bestaat uit:
- 33550 observaties van patiënten in train.csv
- 1 doelvariabele: **stroke**
    - 0 betekent dat de patiënt geen herseninfarct heeft gehad
    - 1 betkent dat de patiënt wel een herseninfarct heeft gehad
- 21 kenmerken die worden gebruikt om een voorspelling te maken
- Zowel numerieke als binaire kenmerken (True of False)

In [20]:
display(train_df.head())
print(train_df.shape)

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,52709,30.0,0,0,63.60,33.3,False,True,False,True,False,False,False,True,False,False,True,False,False,False,True,0
1,72295,75.0,1,0,215.17,48.0,True,False,False,False,True,False,False,False,True,False,True,False,False,True,False,0
2,26451,15.0,0,0,135.22,19.0,False,True,False,True,False,False,False,True,False,False,True,False,False,True,False,0
3,65210,47.0,0,0,64.89,28.2,False,True,False,False,True,False,False,False,True,False,False,True,False,True,False,0
4,69299,49.0,0,0,222.34,28.8,False,True,False,False,True,False,False,False,True,False,True,False,True,False,False,0

(33550, 22)

## Test_df

De dataset test.csv bevat gegevens van patiënten waarvoor de kolom **stroke** ontbreekt. Deze dataset heeft dezelfde kenmerken als train.csv.

We gebruiken test.csv niet om het model te trainen. Nadat we het beste model hebben gekozen, gebruiken we deze dataset om per patiënt een voorspelling te maken. De voorspellingen zetten we vervolgens in een kaggle-submissionbestand

In [21]:
display(test_df.head())
print(test_df.shape)

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,32840,52.0,0,0,97.32,21.8,True,False,False,False,True,False,False,True,False,False,False,True,False,False,True
1,45158,30.0,0,0,227.99,47.7,True,False,False,False,True,False,False,True,False,False,False,True,False,False,True
2,56105,26.0,0,0,113.28,24.4,True,False,False,False,True,False,False,True,False,False,False,True,False,True,False
3,3112,24.0,0,0,79.15,21.0,True,False,False,False,True,False,False,True,False,False,False,True,True,False,False
4,35224,63.0,0,0,89.69,33.3,True,False,False,False,True,False,False,True,False,False,False,True,False,True,False

(8388, 21)

## Submission_df

De dataset **sample_submission.csv** laat zien hoe het bestand voor de Kaggle-inlevering eruit moet zien. Dit bestand bevat twee kolommen:
- **id**: Het unieke patiëntnummer uit test.csv
- **stroke**: De voorspelling van ons model

In [ ]:
display(submission_df.head())
print(submission_df.shape)

      id  stroke
0  32840       1
1  45158       0
2  56105       1
3   3112       0
4  35224       1

(8388, 2)

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **4. Exploratieve data-analyse (EDA)**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **5. Preprocessing & train-test split**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **6. Modelontwikkeling**

In dit hoofdstuk bouwen en vergelijken we verschillende machine-learningmodellen. Het doel van deze modellen is om te voorspellen of een patiënt een verhoogd risico heeft op een herseninfarct.

We gebruiken de opgeschoonde en voorbereide data uit het vorige hoofdstuk. Voor elk model trainen we het model met de trainset en bekijken we daarna hoe goed het model presteert op onze eigen testset.

We vergelijken onder andere k-Nearest Neighbors, Logistic Regression, Support Vector Machine, Decision Tree, Random Forest, Gradient Boosted Decision Trees en XGBoost. Ook maken we een eigen ensemble met meerdere modellen.

Omdat de dataset ongebalanceerd is, passen we bij elk model technieken toe om beter om te gaan met de kleinere groep patiënten met stroke = 1. Daarnaast gebruiken we cross-validation en hyperparameter tuning om de modellen te verbeteren.

Uiteindelijk vergelijken we de resultaten van alle modellen. Het beste model gebruiken we om voorspellingen te maken voor test.csv en in te leveren bij Kaggle.

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.1 K-Nearest Neighbors

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.2 Logistic Regression

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.3 Support Vector Machine (SVM)

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.4 Decision Tree

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.5 Random Forest

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.6 Gradient Boosted Decision Trees

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.7 XGBoost

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

## 6.8 Zelf samengestelde ensemble

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **7. Model Evaluatie**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **8. Modelinterpretatie**

---

<div style="font-family: 'Times New Roman', serif; line-height: 1.3;">

# **9. Conclusie & aanbeveling**